apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pgadmin-secret-external-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: pgadmin-secret
  data:
  - secretKey: admin-password
    remoteRef:
      key: kv/platform/pgadmin
      property: admin-password
