apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: pgadmin-secret-pushsecret
spec:
  deletionPolicy: None
  updatePolicy: IfNotExists
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: vault-backend
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: ClusterGenerator
      name: global-generator
  data:
    - match:
        secretKey: password
        remoteRef:
          property: admin-password
          remoteKey: kv/data/platform/pgadmin