repoURL: http://gitea-http.gitea.svc.cluster.local:3000/gitea_admin/gitops.git
namespace: argocd
projects:
  - name: platform
  - name: network
  - name: security
  - name: monitoring
  - name: system
  - name: datastore
