apiVersion: http.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: http
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  credentials:
    source: None