apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: cluster-registration
spec:
  provider:
    kubernetes:
      # CREATE CLUSTER ROLE TO GET NAMESPACE AND APPLY IN ARGO NAME SPACE
      remoteNamespace: argo-cd
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
          namespace: external-secrets
      auth:
        serviceAccount:
          name: external-secrets
          namespace: external-secrets