apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: stalwart-pg-externalsecret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: stalwart-pg
  dataFrom:
    - extract:
        key: datastore/postgres/lab/stalwart
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: stalwart-s3-externalsecret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: stalwart-s3
  data:
    - secretKey: access-key
      remoteRef:
        key: storage/seaweedfs/stalwart
        property: access-key
    - secretKey: secret-key
      remoteRef:
        key: storage/seaweedfs/stalwart
        property: secret-key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: stalwart-admin-externalsecret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: stalwart-admin
  data:
    - secretKey: password
      remoteRef:
        key: mail/stalwart/admin
        property: password
