apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - externalsecret.yaml
  - pushsecret.yaml

helmCharts:
  - name: stalwart-mail-ha
    repo: https://l4gdev.github.io/helm-charts
    version: 0.1.2
    releaseName: stalwart
    namespace: stalwart
    valuesFile: values.yaml
