apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ printf "%s" (include "common.names.fullname" .)) | trunc 63 | trimSuffix "-" }}-externalsecret
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: keycloak-secret
  data:
  - secretKey: admin
    remoteRef:
      key: kv/apps/keycloak
      property: admin
  - secretKey: host
    remoteRef:
      key: kv/database/postgres/users/keycloak
      property: host
  - secretKey: port
    remoteRef:
      key: kv/database/postgres/users/keycloak
      property: port
  - secretKey: user
    remoteRef:
      key: kv/database/postgres/users/keycloak
      property: user
  - secretKey: dbname
    remoteRef:
      key: kv/database/postgres/users/keycloak
      property: dbname
  - secretKey: password
    remoteRef:
      key: kv/database/postgres/users/keycloak
      property: password