apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-externalsecret
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: grafana-secrets
  data:
  - secretKey: GRAFANA_SSO_CLIENT_SECRET
    remoteRef:
      key: kv/apps/keycloak
      property: client_grafana
