name: lab
postgresVersion: 16
pgBouncerReplicas: 1
monitoring: true
users:
  - name: postgres
    databases:
      - postgres
    options: "SUPERUSER"
    password:
      type: AlphaNumeric
  - name: keycloak
    databases:
      - keycloak
    password:
      type: AlphaNumeric
  - name: waseelah
    databases:
      - waseelah
    password:
      type: AlphaNumeric
metadata:
  labels:
      crunchy-userinit.ramblurr.github.com/enabled: "true"
      crunchy-userinit.ramblurr.github.com/superuser: "postgres"
