apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-unseal-externalsecret
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: vault-unseal-conf
    template:
      engineVersion: v2
      data:
      {{ (.Files.Glob "files/*").AsConfig | indent 6 }}
  data:
  - secretKey: keys
    remoteRef:
      key: kv/vault
      property: keys
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-externalsecret
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: vault-token
  data:
  - secretKey: token
    remoteRef:
      key: kv/vault
      property: root_token
