apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-unseal-externalsecret
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: vault-unseal-conf
    template:
      engineVersion: v2
      data:
        vault-unseal.yaml: |
        allow_single_node: true
        check_interval: 15s
        max_check_interval: 30m
        vault_nodes:
          - "http://vault:8200"
        unseal_tokens:
          "{{ `{{range .keys}}` }}"
          - "{{ `{{.}}` }}"
          "{{ `{{end}}` }}"
  data:
  - secretKey: keys
    remoteRef:
      key: kv/vault
      property: keys
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-externalsecret
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: vault-token
  data:
  - secretKey: token
    remoteRef:
      key: kv/vault
      property: root_token
