apiVersion: v1
kind: Namespace
metadata:
  name: capi-k3s-control-plane-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: ControlPlaneProvider
metadata:
  name: k3s
  namespace: capi-k3s-control-plane-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  version: v0.4.0
  fetchConfig:
    url: https://github.com/k3s-io/cluster-api-k3s/releases/v0.4.0/control-plane-components.yaml
