apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hetzner
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: hetzner
    template:
      engineVersion: v2
      data:
        hcloud: "{{ .hcloudToken }}"
  data:
    - secretKey: hcloudToken
      remoteRef:
        key: clusters/hetzner/k3s
        property: hcloud-token
