apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hetzner-k3s

resources:
  - credentials.yaml
  - cluster.yaml
  - control-plane.yaml
  - workers.yaml
  - health.yaml
  - addons.yaml
