apiVersion: batch/v1
kind: Job
metadata:
  name: terralist-register
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "1"
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: Never
      securityContext:
        fsGroup: 101
      containers:
        - name: register
          image: alpine:3.20
          command: ["/bin/sh", "-c"]
          args:
            - "apk add --no-cache curl jq gnupg >/dev/null && sh /scripts/register.sh"
          env:
            - name: TERRALIST_API
              value: http://terralist.terralist.svc.cluster.local:5758
            - name: FILESERVER
              value: http://127.0.0.1:8080
            - name: MASTER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: terralist-secret
                  key: master-api-key
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: "1"
              memory: 512Mi
          volumeMounts:
            - name: files
              mountPath: /srv
            - name: script
              mountPath: /scripts
              readOnly: true
      volumes:
        - name: files
          persistentVolumeClaim:
            claimName: terralist-files
        - name: script
          configMap:
            name: terralist-register-script
