apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: vault-pushsecret
spec:
  deletionPolicy: None
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: vault-backend
  selector:
    secret:
      name: vault-init-data
  data:
    - match:
        remoteRef:
          remoteKey: security/vault/init-data