apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backstage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: backstage
  dataFrom:
  - extract:
      key: platform/backstage