apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: open-webui
  repo: https://helm.openwebui.com/
  version: 14.2.0
  releaseName: openwebui
  namespace: ai
  valuesFile: values.yaml
