ollama:
  enabled: false
pipelines:
  enabled: false
tika:
  enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
terminals:
  enabled: true

podAnnotations:
  inject-certs: "enabled"

ingress:
  enabled: true
  class: nginx
  annotations:
    cert-manager.io/cluster-issuer: lab-issuer
  host: openwebui.lab.com
  tls: true

persistence:
  size: 2Gi

openaiBaseApiUrls:
  - "http://litellm.litellm:4000"
openaiApiKeys:
  - "sk-FfcXHcHHKXwCqgEjOq"

sso:
  enabled: true
  enableSignup: true
  oidc:
    enabled: true
    clientId: openwebui
    clientSecret: "vuVdKVZzNzxuLTspjD6q7zUQ4JXxNoJ3"
    providerUrl: "https://sso.lab.com/realms/lab/.well-known/openid-configuration"
    providerName: "Keycloak"
    scopes: "openid email profile"

extraEnvVars:
  - name: ENABLE_PERSISTENT_CONFIG
    value: "False"
  - name: WEBUI_URL
    value: "https://openwebui.lab.com"
  - name: NODE_EXTRA_CA_CERTS
    value: "/etc/ssl/certs/ca.crt"
  - name: DATABASE_URL
    valueFrom:
      secretKeyRef:
        name: openwebui-postgres
        key: uri
