apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bulwark-externalsecret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: bulwark-secret
  data:
    - secretKey: session-secret
      remoteRef:
        key: mail/bulwark/session-secret
        property: session-secret
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bulwark-oidc-externalsecret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: bulwark-oidc
  data:
    - secretKey: client-secret
      remoteRef:
        key: platform/keycloak/clients/bulwark
        property: secret-key
