---
apiVersion: capsule.clastix.io/v1beta2
kind: ResourcePool
metadata:
  name: medium-tenant-quota
spec:
  selectors:
  - matchLabels:
      capsule.clastix.io/tenant-quota: medium
  quota:
    hard:
      requests.cpu: "8"
      requests.memory: 16Gi
      limits.cpu: "16"
      limits.memory: 32Gi
      requests.storage: 250Gi
---
apiVersion: capsule.clastix.io/v1beta2
kind: TenantResource
metadata:
  name: medium-tenant-quota
spec:
  resyncPeriod: 60s
  resources:
    - namespaceSelector:
        matchLabels:
          capsule.clastix.io/tenant-quota: medium
      rawItems:
        - apiVersion: v1
          kind: LimitRange
          metadata:
            name: default-limits
          spec:
            limits:
            - default:
                cpu: 300m
              defaultRequest:
                cpu: 200m
              max:
                cpu: 500m
              min:
                cpu: 50m
              type: Container
