apiVersion: v2
name: pgo
version: 0.0.0
dependencies:
  - name: pgo
    version: 5.6.0
    repository: oci://registry.developers.crunchydata.com/crunchydata
  - name: crunchy-userinit-controller
    version: 0.0.4
    repository: https://ramblurr.github.io/crunchy-userinit-controller
