apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: coder-terralist-externalsecret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: coder-terralist
  data:
    - secretKey: master-api-key
      remoteRef:
        key: platform/terralist/master-api-key
        property: master-api-key
