apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - externalsecret.yaml
  - job.yaml

configMapGenerator:
  - name: coder-providers-push-script
    files:
      - upload.sh
