apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: terralist-token-signing-pushsecret
spec:
  deletionPolicy: None
  updatePolicy: IfNotExists
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: vault-backend
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: ClusterGenerator
      name: strong-password-generator
  data:
    - match:
        secretKey: password
        remoteRef:
          property: token-signing-secret
          remoteKey: platform/terralist/token-signing-secret
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: terralist-cookie-pushsecret
spec:
  deletionPolicy: None
  updatePolicy: IfNotExists
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: vault-backend
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: ClusterGenerator
      name: strong-password-generator
  data:
    - match:
        secretKey: password
        remoteRef:
          property: cookie-secret
          remoteKey: platform/terralist/cookie-secret
