controllers:
  main:
    pod:
      annotations:
        inject-certs: "enabled"
    containers:
      app:
        image:
          tag: v0.10.6
        env:
          TERRALIST_URL: "https://terralist.lab.com"
          TERRALIST_LOG_LEVEL: "info"

          TERRALIST_DATABASE_BACKEND: "sqlite"
          TERRALIST_SQLITE_PATH: "/data/terralist.db"
          TERRALIST_MODULES_STORAGE_RESOLVER: "local"
          TERRALIST_PROVIDERS_STORAGE_RESOLVER: "local"
          TERRALIST_LOCAL_STORE: "/data"

          TERRALIST_MODULES_ANONYMOUS_READ: "true"
          TERRALIST_PROVIDERS_ANONYMOUS_READ: "true"
          TERRALIST_FETCH_ALLOW_PRIVATE_ADDRESSES: "true"

          TERRALIST_OAUTH_PROVIDER: "oidc"
          TERRALIST_OI_CLIENT_ID: "terralist"
          TERRALIST_OI_HOST: "https://sso.lab.com/realms/lab"

          TERRALIST_RBAC_DEFAULT_ROLE: "anonymous"
          TERRALIST_RBAC_POLICY_PATH: "/rbac/policy.csv"

          TERRALIST_OI_CLIENT_SECRET:
            valueFrom:
              secretKeyRef:
                name: terralist-secret
                key: oidc-client-secret
          TERRALIST_TOKEN_SIGNING_SECRET:
            valueFrom:
              secretKeyRef:
                name: terralist-secret
                key: token-signing-secret
          TERRALIST_LOCAL_TOKEN_SIGNING_SECRET:
            valueFrom:
              secretKeyRef:
                name: terralist-secret
                key: token-signing-secret
          TERRALIST_COOKIE_SECRET:
            valueFrom:
              secretKeyRef:
                name: terralist-secret
                key: cookie-secret
          TERRALIST_MASTER_API_KEY:
            valueFrom:
              secretKeyRef:
                name: terralist-secret
                key: master-api-key

configMaps:
  rbac:
    enabled: true
    data:
      policy.csv: |
        g, abdo@lab.com, role:admin

persistence:
  data:
    accessMode: ReadWriteOnce
    size: 10Gi
  rbac:
    enabled: true
    type: configMap
    identifier: rbac
    globalMounts:
      - path: /rbac
        readOnly: true

ingress:
  main:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: lab-issuer
      gethomepage.dev/enabled: "true"
      gethomepage.dev/name: "Terralist"
      gethomepage.dev/description: "Private Terraform Registry"
      gethomepage.dev/group: "Platform"
    hosts:
      - host: terralist.lab.com
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http
    tls:
      - secretName: terralist-tls
        hosts:
          - terralist.lab.com
