apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: openwebui-postgres
  namespace: ai
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: openwebui-postgres
  dataFrom:
    - extract:
        key: datastore/postgres/lab/openwebui
