apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: crossplane
  repo: https://charts.crossplane.io/stable
  version: 2.0.2
  includeCRDs: true
  namespace: crossplane
  releaseName: crossplane
  valuesFile: values.yaml