apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bifrost-encryption-key-externalsecret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: bifrost-encryption-key
  dataFrom:
  - extract:
      key: platform/bifrost/encryption-key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bifrost-admin-credentials-externalsecret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: bifrost-admin-credentials
  dataFrom:
  - extract:
      key: platform/bifrost/admin-credentials
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bifrost-postgres-externalsecret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: bifrost-postgres
  dataFrom:
  - extract:
      key: datastore/postgres/lab/bifrost
