apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: bifrost-encryption-key-pushsecret
spec:
  deletionPolicy: None
  updatePolicy: IfNotExists
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: vault-backend
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: ClusterGenerator
      name: strong-password-generator
  data:
    - match:
        secretKey: password
        remoteRef:
          property: encryption-key
          remoteKey: platform/bifrost/encryption-key
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: bifrost-admin-pushsecret
spec:
  deletionPolicy: None
  updatePolicy: IfNotExists
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: vault-backend
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: ClusterGenerator
      name: strong-password-generator
  template:
    engineVersion: v2
    data:
      username: "admin"
      password: "{{ .password }}"
  data:
    - match:
        secretKey: username
        remoteRef:
          property: username
          remoteKey: platform/bifrost/admin-credentials
    - match:
        secretKey: password
        remoteRef:
          property: password
          remoteKey: platform/bifrost/admin-credentials
