apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: inject-certs
  annotations:
    policies.kyverno.io/title: Add Certificates as a Volume
    policies.kyverno.io/category: Sample
    policies.kyverno.io/subject: Pod,Volume
    kyverno.io/kyverno-version: 1.6.0
    kyverno.io/kubernetes-version: "1.21"
    policies.kyverno.io/minversion: 1.5.0
    pod-policies.kyverno.io/autogen-controllers: DaemonSet,Deployment,Job,StatefulSet
    policies.kyverno.io/description: >-
      In some cases you would need to trust custom CA certificates for all the containers of a Pod.
      It makes sense to be in a ConfigMap so that you can automount them by only setting an annotation.
      This policy adds a volume to all containers in a Pod containing the certificate if the annotation
      called `inject-certs` with value `enabled` is found.
spec:
  background: false
  rules:
  - name: add-ssl-certs
    match:
      any:
      - resources:
          kinds:
          - Pod
    preconditions:
      all:
      - key: '{{request.object.metadata.annotations."inject-certs" || ""}}'
        operator: Equals
        value: enabled
      - key: "{{request.operation || 'BACKGROUND'}}"
        operator: AnyIn
        value:
          - CREATE
          - UPDATE
    mutate:
      patchStrategicMerge:
        spec:
          hostAliases:
          - hostnames:
            - argo.lab.com
            - home.lab.com
            - sso.lab.com
            - sso.admin.lab.com
            - vault.lab.com
            - registry.lab.com
            - portal.lab.com
            ip: 10.43.41.204
          volumes:
          - name: etc-ssl-certs
            secret:
              secretName: lab.com
          initContainers:
            - (name): "*"
              volumeMounts:
                - name: etc-ssl-certs
                  mountPath: /etc/ssl/certs/ca.crt
                  subPath: ca.crt
                  readOnly: true
          containers:
            - (name): "*"
              volumeMounts:
                - name: etc-ssl-certs
                  mountPath: /etc/ssl/certs/ca.crt
                  subPath: ca.crt
                  readOnly: true
