apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: replace-bitnami-repo
  annotations:
    policies.kyverno.io/title: Replace Bitnami Images with Legacy Repo
    pod-policies.kyverno.io/autogen-controllers: none
    policies.kyverno.io/category: Sample
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    kyverno.io/kyverno-version: 1.7.2
    policies.kyverno.io/minversion: 1.6.0
    kyverno.io/kubernetes-version: "1.23"
    policies.kyverno.io/description: >-
      Mutates any image from Bitnami to use the `bitnamilegacy` repository.
      Example: docker.io/bitnami/postgresql -> bitnamilegacy/postgresql.
spec:
  background: false
  rules:
    - name: replace-bitnami-in-containers
      match:
        any:
        - resources:
            kinds:
            - Pod
      mutate:
        foreach:
        - list: "request.object.spec.containers"
          patchStrategicMerge:
            spec:
              containers:
              - name: "{{ element.name }}"
                image: "{{ regex_replace_all('^(?:[a-z0-9.-]+/)?bitnami/(.*)$', '{{element.image}}', 'bitnamilegacy/$1') }}"
    - name: replace-bitnami-in-initcontainers
      match:
        any:
        - resources:
            kinds:
            - Pod
      preconditions:
        all:
        - key: "{{ request.object.spec.initContainers[] || `[]` | length(@) }}"
          operator: GreaterThanOrEquals
          value: 1
      mutate:
        foreach:
        - list: "request.object.spec.initContainers"
          patchStrategicMerge:
            spec:
              initContainers:
              - name: "{{ element.name }}"
                image: "{{ regex_replace_all('^(?:[a-z0-9.-]+/)?bitnami/(.*)$', '{{element.image}}', 'bitnamilegacy/$1') }}"
