apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-dynamic-plugins
  namespace: backstage
data:
  dynamic-plugins.yaml: |
    includes:
      - "dynamic-plugins.default.yaml"
    plugins:
      - package: ./dynamic-plugins/dist/backstage-community-plugin-catalog-backend-module-keycloak-dynamic
        disabled: false
      - package: ./dynamic-plugins/dist/backstage-plugin-kubernetes-backend-dynamic
        disabled: false
      - package: ./dynamic-plugins/dist/red-hat-developer-hub-backstage-plugin-global-header
        disabled: false
      - package: ./dynamic-plugins/dist/backstage-plugin-kubernetes
        disabled: false
      - package: ./dynamic-plugins/dist/backstage-community-plugin-topology
        disabled: false
      - package: ./dynamic-plugins/dist/backstage-plugin-notifications
        disabled: false
      - package: ./dynamic-plugins/dist/backstage-plugin-notifications-backend-dynamic
        disabled: false
      - package: ./dynamic-plugins/dist/backstage-plugin-signals-backend-dynamic
        disabled: false
      - package: ./dynamic-plugins/dist/backstage-plugin-signals
        disabled: false  
      - package: ./dynamic-plugins/dist/backstage-community-plugin-analytics-provider-segment
        disabled: true
      - package: ./dynamic-plugins/dist/backstage-community-plugin-scaffolder-backend-module-kubernetes-dynamic
        disabled: true
      - package: ./dynamic-plugins/dist/backstage-community-plugin-scaffolder-backend-module-quay-dynamic
        disabled: true
      - package: ./dynamic-plugins/dist/backstage-community-plugin-scaffolder-backend-module-regex-dynamic
        disabled: true
      - package: ./dynamic-plugins/dist/red-hat-developer-hub-backstage-plugin-analytics-module-adoption-insights-dynamic
        disabled: true
      - package: ./dynamic-plugins/dist/red-hat-developer-hub-backstage-plugin-quickstart
        disabled: true
      - package: ./dynamic-plugins/dist/red-hat-developer-hub-backstage-plugin-catalog-backend-module-marketplace-dynamic
        disabled: true
      - package: ./dynamic-plugins/dist/red-hat-developer-hub-backstage-plugin-marketplace-backend-dynamic
        disabled: true
      - package: ./dynamic-plugins/dist/red-hat-developer-hub-backstage-plugin-marketplace
        disabled: true
      - package: ./dynamic-plugins/dist/backstage-plugin-scaffolder-backend-module-github-dynamic
        disabled: false
      - package: ./dynamic-plugins/dist/roadiehq-scaffolder-backend-module-utils-dynamic
        disabled: false
      - package: ./dynamic-plugins/dist/roadiehq-scaffolder-backend-module-http-request-dynamic
        disabled: false
      - package: ./dynamic-plugins/dist/backstage-community-plugin-catalog-backend-module-scaffolder-relation-processor-dynamic
        disabled: false
      - package: ./dynamic-plugins/dist/backstage-community-plugin-rbac
        disabled: true
              
      - disabled: false
        package: "https://github.com/TheCodingSheikh/backstage-plugins/releases/download/thecodingsheikh-backstage-plugin-scaffolder-field-validator-v1.0.1/thecodingsheikh-backstage-plugin-scaffolder-field-validator-dynamic-1.0.1.tgz"
        integrity: sha512-9mC3S7eJ6PnibOEMUSTQBTuy2NbXwLVt31fpFqy09bogQes8u50vGq0BBHEWcjWHE89vwyyyEqiFTT2qv1ExqQ==
        pluginConfig:
          dynamicPlugins:
            frontend:
              thecodingsheikh.backstage-plugin-scaffolder-field-validator:
                scaffolderFieldExtensions:
                  - importName: ScaffolderFieldValidatorExtension

      - disabled: false
        package: "https://github.com/TheCodingSheikh/backstage-plugins/releases/download/thecodingsheikh-backstage-plugin-multi-owner-v1.0.4/thecodingsheikh-backstage-plugin-multi-owner-dynamic-1.0.4.tgz"
        integrity: sha512-UqWmA5girtgq0rFfVkYC9Orib22bZtjFOlMiGGzhXKDEkC9XsmVhOKmGNyywljxFINjvH48P7YwfqR60uUNGmA==
        pluginConfig:
          dynamicPlugins:
            frontend:
              thecodingsheikh.backstage-plugin-multi-owner:
                mountPoints:
                  - mountPoint: entity.page.overview/cards
                    importName: EntityMultiOwnerCard
                    config:
                      layout:
                        gridColumnEnd:
                          lg: "span 8"
                          xs: "span 12"
                      if:
                        allOf:
                          - isMultiOwnerAvailable

      - disabled: false
        package: "https://github.com/TheCodingSheikh/backstage-plugins/releases/download/thecodingsheikh-backstage-plugin-entity-scaffolder-v0.3.1/thecodingsheikh-backstage-plugin-entity-scaffolder-dynamic-0.3.1.tgz"
        integrity: sha512-1O3hDU+rt9e29P2n2Qoy0kO5DSX0CrWWbf/hRcLjHSXAXGUctCEhlnt6Wqgmb5+vOxryZIvkISDVe7O1N0oClw==
        pluginConfig:
          dynamicPlugins:
            frontend:
              thecodingsheikh.backstage-plugin-entity-scaffolder:
                entityTabs:
                  - path: /entity-scaffolder
                    title: Manage
                    mountPoint: entity.page.entity-scaffolder
                mountPoints:
                  - mountPoint: entity.page.entity-scaffolder/cards
                    importName: EntityScaffolderContent
                    config:
                      layout:
                        gridColumn: "1 / -1"
                      if:
                        allOf:
                          - isEntityScaffolderAvailable
        
      - disabled: false
        package: "https://github.com/TheCodingSheikh/backstage-plugins/releases/download/thecodingsheikh-backstage-plugin-catalog-backend-module-multi-owner-processor-v1.0.4/thecodingsheikh-backstage-plugin-catalog-backend-module-multi-owner-processor-dynamic-1.0.4.tgz"
        integrity: sha512-U+RLFz2Jy+UgMzdrwYiZIOA9hFhFZYKDSmuzvD27xchWZ2QuttaTNM5ahh8kP2Eil/OJ7P5GZV1VNvT8BOXadg==

      - disabled: true
        package: "https://github.com/TheCodingSheikh/backstage-plugins/releases/download/terasky-backstage-plugin-kubernetes-ingestor-v3.14.0/terasky-backstage-plugin-kubernetes-ingestor-dynamic-3.14.0.tgz"
        integrity: sha512-lm8Oukvg+v1MGnMXNxzWQG7I0LopaIYC/hJRxGsU9LOdytwuyPs1Kb4kfev8/aAvkNsoAlf6UjcKKESKSvr1ZQ==
        pluginConfig:
          kubernetesIngestor:
            mappings:
              namespaceModel: 'default'
              nameModel: 'name-kind'
              titleModel: 'name'
              systemModel: 'namespace'
              referencesNamespaceModel: 'default'
            components:
              enabled: true
              taskRunner:
                frequency: 20
                timeout: 600
              onlyIngestAnnotatedResources: true
            crossplane:
              enabled: false
        
      - disabled: false
        package: "https://github.com/TheCodingSheikh/backstage-plugins/releases/download/roadiehq-plugin-scaffolder-frontend-module-http-request-field-v2.3.0/roadiehq-plugin-scaffolder-frontend-module-http-request-field-dynamic-2.3.0.tgz"
        integrity: sha512-Xn6HAEC2H92XOBDB75CBXzfnQuF0ml9LEYfwAQa6QtBLLPUiNXEUjGW/TtrqgGpWsYxyTWZ6wHJUqEYHjBus2w==
        pluginConfig:
          dynamicPlugins:
            frontend:
              roadiehq.plugin-scaffolder-frontend-module-http-request-field:
                scaffolderFieldExtensions:
                  - importName: SelectFieldFromApiExtension
        
      - disabled: false
        package: "https://github.com/TheCodingSheikh/backstage-plugins/releases/download/backstage-community-plugin-vault-v0.19.0/backstage-community-plugin-vault-dynamic-0.19.0.tgz"
        integrity: sha512-iIQtK5HMMHf0rl8ut9wf/aOrNSWk9B/xq7HS9NcY3g0Xcf6+DkAtFWt9iLCjKmvQM+WUvv/U0JS0tQvAFukxwA==
        pluginConfig:
          vault:
            baseUrl: ${VAULT_BASE_URL}
            publicUrl: ${VAULT_PUBLIC_URL}
            auth:
              type: static
              secret: ${VAULT_TOKEN}
            secretEngine: secrets
            kvVersion: 2
          dynamicPlugins:
            frontend:
              backstage-community.plugin-vault:
                mountPoints:
                  - mountPoint: entity.page.overview/cards
                    importName: EntityVaultCard
                    config:
                      layout:
                        gridColumnEnd:
                          lg: "span 8"
                          xs: "span 12"
                      if:
                        allOf:
                          - isKind: component
                          - hasAnnotation: vault.io/secrets-path

      - disabled: false
        package: "https://github.com/TheCodingSheikh/backstage-plugins/releases/download/backstage-community-plugin-vault-backend-v0.21.0/backstage-community-plugin-vault-backend-dynamic-0.21.0.tgz"
        integrity: sha512-7cvACKlbvRBmljQAOMdzsawV2pGgwYqUIpwNd3ic/+4GXynYbBAjY2cBj24UbjDp3tlEeCojnuL4KFyzrqESYg==

      - disabled: false
        package: "https://github.com/TheCodingSheikh/backstage-plugins/releases/download/backstage-community-plugin-grafana-v0.17.0/backstage-community-plugin-grafana-dynamic-0.17.0.tgz"
        integrity: sha512-L57wnDks1s7hGdH+CT4Quc63SmzU0R3HzuD405Wq2d7zjrBm7mY7/luTvJ49bI2j++mQYVcV+YZhMB43kFesyw==
        pluginConfig:
          proxy:
            endpoints:
              /grafana/api:
                target: ${GRAFANA_ENDPOINT}/
                headers:
                  Authorization: "Bearer ${GRAFANA_TOKEN}"
          grafana:
            domain: ${GRAFANA_PUBLIC_DOMAIN}
          dynamicPlugins:
            frontend:
              backstage-community.plugin-grafana:
                entityTabs:
                  - path: /grafana
                    title: Grafana
                    mountPoint: entity.page.grafana
                mountPoints:
                  - mountPoint: entity.page.grafana/cards
                    importName: EntityOverviewDashboardViewer
                    config:
                      layout:
                        gridColumn: "1 / -1"
                      if:
                        allOf:
                          - isKind: component
                          - hasAnnotation: grafana/overview-dashboard
                  - mountPoint: entity.page.grafana/cards
                    importName: EntityGrafanaDashboardsCard
                    config:
                      layout:
                        gridColumnEnd:
                          lg: "span 8"
                          xs: "span 12"
                      if:
                        allOf:
                          - isKind: component
                          - hasAnnotation: grafana/dashboard-selector
                  - mountPoint: entity.page.grafana/cards
                    importName: EntityGrafanaAlertsCard
                    config:
                      layout:
                        gridColumnEnd:
                          lg: "span 8"
                          xs: "span 12"
                      if:
                        allOf:
                          - isKind: component
                          - anyOf:
                              - hasAnnotation: grafana/alert-label-selector
                              - hasAnnotation: grafana/tag-selector