alertmanager:
  enabled: false
  # config:
  #   global:
  #     resolve_timeout: 5m
  #     slack_api_url: "https://hooks.slack.com/services/"
  #   route:
  #     receiver: "slack-notifications"
  #     repeat_interval: 12h
  #     routes:
  #       - receiver: "slack-notifications"
  #   receivers:
  #     - name: "slack-notifications"
  #       slack_configs:
  #         - channel: "#basier"
  #           send_resolved: true
  #           title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
  #           text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
        
grafana:
  enabled: false
  forceDeployDashboards: true
prometheus:
  thanosService:
    enabled: true
  thanosServiceMonitor:
    enabled: true
  prometheusSpec:
    enableRemoteWriteReceiver: true
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    thanos:
      objectStorageConfig:
        existingSecret:
          name: thanos-objstore
          key: objstore.yml