apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-unseal-externalsecret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: vault-unseal-conf
    template:
      engineVersion: v2
      data:
        vault-unseal.yaml: |
          environment: dev
          check_interval: 15s
          max_check_interval: 30m
          vault_nodes:
            - http://vault:8200
            - http://vault:8200
            - http://vault:8200
          tls_skip_verify: true
          unseal_tokens:
          {{- range .unseal_keys_b64 | fromJson }}
            - "{{ . }}"
          {{- end }}
  data:
  - secretKey: unseal_keys_b64
    remoteRef:
      key: security/vault/init-data
      property: unseal_keys_b64
