- hosts: lab
  tasks:
  - name: Install zsh
    ansible.builtin.apt:
      name: zsh
      state: present
    become: true

  - name: Install zsh
    ansible.builtin.apt:
      name: fonts-powerline
      state: present
    become: true

  - name: Set user shell to zsh
    ansible.builtin.user:
      name: "{{ ansible_user }}"
      shell: /bin/zsh
    become: true

  - name: Install Oh My Zsh
    ansible.builtin.git:
      repo: https://github.com/ohmyzsh/ohmyzsh.git
      dest: "{{ ansible_env.HOME }}/.oh-my-zsh"

  - name: Copy .zshrc template
    ansible.builtin.copy:
      src: "{{ ansible_env.HOME }}/.oh-my-zsh/templates/zshrc.zsh-template"
      dest: "{{ ansible_env.HOME }}/.zshrc"
      remote_src: yes
        
  - name: Clone Powerlevel10k theme
    git:
      repo: https://github.com/romkatv/powerlevel10k.git
      dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/themes/powerlevel10k"

  - name: Clone zsh-autosuggestions 
    git:
      repo: https://github.com/zsh-users/zsh-autosuggestions.git
      dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"

  - name: Clone zsh-syntax-highlighting
    git:
      repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
      dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"

  - name: Set ZSH_THEME in .zshrc
    ansible.builtin.lineinfile:
      path: "{{ ansible_env.HOME }}/.zshrc"
      regexp: '^ZSH_THEME='
      line: 'ZSH_THEME="powerlevel10k/powerlevel10k"'
      create: yes

  - name: Set oh-my-zsh plugins in .zshrc
    ansible.builtin.lineinfile:
      path: "{{ ansible_env.HOME }}/.zshrc"
      regexp: '^plugins='
      line: 'plugins=(git zsh-autosuggestions zsh-syntax-highlighting)'
      create: yes

