apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: coder-externalsecret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: coder-secret
  data:
    - secretKey: pg-connection-url
      remoteRef:
        key: datastore/postgres/lab/coder
        property: uri
    - secretKey: oidc-client-secret
      remoteRef:
        key: platform/keycloak/clients/coder
        property: secret-key
