apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: coder-admin-pushsecret
spec:
  deletionPolicy: None
  updatePolicy: IfNotExists
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: vault-backend
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: ClusterGenerator
      name: strong-password-generator
  data:
    - match:
        secretKey: password
        remoteRef:
          property: password
          remoteKey: platform/coder/users/admin
