apiVersion: v1
kind: Service
metadata:
  name: coder-metrics
  labels:
    app.kubernetes.io/name: coder-metrics
spec:
  selector:
    app.kubernetes.io/name: coder
    app.kubernetes.io/instance: coder
  ports:
    - name: prometheus-http
      port: 2112
      targetPort: 2112
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: coder
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: coder-metrics
  endpoints:
    - port: prometheus-http
      interval: 30s
