apiVersion: v1
kind: ConfigMap
metadata:
  name: coder-terraformrc
data:
  terraformrc: |
    provider_installation {
      network_mirror {
        url = "https://terralist.lab.com/files/mirror/"
      }
    }
