apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: thanos-objstore
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: thanos-objstore
    template:
      engineVersion: v2
      data:
        objstore.yml: |
          type: S3
          config:
            bucket: "thanos"
            endpoint: "seaweedfs-all-in-one.seaweedfs.svc.cluster.local:8333"
            region: "us-east-1"
            access_key: "{{ .access_key }}"
            secret_key: "{{ .secret_key }}"
            insecure: true
            signature_version2: false
            bucket_lookup_type: "path"
  data:
    - secretKey: access_key
      remoteRef:
        key: storage/seaweedfs/monitoring
        property: access-key
    - secretKey: secret_key
      remoteRef:
        key: storage/seaweedfs/monitoring
        property: secret-key
