grafana:
  admin:
    existingSecret: grafana-secrets
    userKey: admin-user
    passwordKey: admin-password
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      traefik.ingress.kubernetes.io/router.tls: "true"
    hosts:
      - &host grafana.lab.alsheykh.com
    tls:
      - secretName: grafana-general-tls
        hosts:
          - *host
  serviceMonitor:
    enabled: true
  sidecar:
    dashboards:
      enabled: true
      searchNamespace: ALL
      label: grafana_dashboard
      folderAnnotation: grafana_folder
      provider:
        disableDelete: true
        foldersFromFilesStructure: true
    datasources:
      enabled: true
      searchNamespace: ALL
      labelValue: ""
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: default
          disableDeletion: false
          editable: true
          folder: ""
          options:
            path: /var/lib/grafana/dashboards/default
          orgId: 1
          type: file
        - name: postgres
          orgId: 1
          folder: Postgres
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/postgres
  dashboards:
    default:
      cert-manager:
        url: https://raw.githubusercontent.com/monitoring-mixins/website/master/assets/cert-manager/dashboards/cert-manager.json
        datasource: Prometheus
      external-secrets:
        url: https://raw.githubusercontent.com/external-secrets/external-secrets/main/docs/snippets/dashboard.json
        datasource: Prometheus
    postgres:
      crunchy-pgbackrest:
        url: https://raw.githubusercontent.com/CrunchyData/postgres-operator-examples/main/kustomize/monitoring/grafana/dashboards/pgbackrest.json
        datasource: Prometheus
      crunchy-pod-details:
        url: https://raw.githubusercontent.com/CrunchyData/postgres-operator-examples/main/kustomize/monitoring/grafana/dashboards/pod_details.json
        datasource: Prometheus
      crunchy-postgresql-details:
        url: https://raw.githubusercontent.com/CrunchyData/postgres-operator-examples/main/kustomize/monitoring/grafana/dashboards/postgresql_details.json
        datasource: Prometheus
      crunchy-postgresql-overview:
        url: https://raw.githubusercontent.com/CrunchyData/postgres-operator-examples/main/kustomize/monitoring/grafana/dashboards/postgresql_overview.json
        datasource: Prometheus
      crunchy-postgresql-service_health:
        url: https://raw.githubusercontent.com/CrunchyData/postgres-operator-examples/main/kustomize/monitoring/grafana/dashboards/postgresql_service_health.json
        datasource: Prometheus
      crunchy-prometheus-alerts:
        url: https://raw.githubusercontent.com/CrunchyData/postgres-operator-examples/main/kustomize/monitoring/grafana/dashboards/prometheus_alerts.json
        datasource: Prometheus
      crunchy-query-statistics:
        url: https://raw.githubusercontent.com/CrunchyData/postgres-operator-examples/main/kustomize/monitoring/grafana/dashboards/query_statistics.json
        datasource: Prometheus
  datasources:
    datasources.yaml:
      apiVersion: 1
      deleteDatasources:
        - name: Alertmanager
          orgId: 1
        - name: Prometheus
          orgId: 1
        - name: Loki
          orgId: 1
      datasources: 
      - name: Prometheus 
        type: prometheus 
        uid: prometheus 
        access: proxy 
        url: http://prometheus-operated.kube-prometheus-stack.svc:9090 
        jsonData: 
          timeInterval: 1m 
      - name: Loki 
        type: loki 
        uid: loki 
        access: proxy 
        url: http://loki-headless.loki.svc:3100 
        jsonData: 
          maxLines: 250 
      - name: Alertmanager 
        type: alertmanager 
        uid: alertmanager 
        access: proxy 
        url: http://alertmanager-operated.kube-prometheus-stack.svc:9093 
        jsonData: 
          implementation: prometheus
  env:
    GF_DATE_FORMATS_USE_BROWSER_LOCALE: true
    GF_EXPLORE_ENABLED: true
    GF_SECURITY_ANGULAR_SUPPORT_ENABLED: true
  imageRenderer:
      enabled: true
  envValueFrom:
    GRAFANA_SSO_CLIENT_SECRET:
      secretKeyRef:
        name: grafana-secrets
        key: GRAFANA_SSO_CLIENT_SECRET
  envFromSecret: grafana-secrets
  grafana.ini:
    server:
      root_url: https://grafana.lab.alsheykh.com
    auth.generic_oauth:
      enabled: true
      allow_sign_up: true
      name: SSO
      client_id: grafana
      client_secret: $__env{GRAFANA_SSO_CLIENT_SECRET}
      scopes: openid email profile grafana
      email_attribute_path: email
      login_attribute_path: username
      name_attribute_path: full_name
      auth_url: https://auth.lab.alsheykh.com/realms/lab/protocol/openid-connect/auth
      token_url: https://auth.lab.alsheykh.com/realms/lab/protocol/openid-connect/token
      api_url: https://auth.lab.alsheykh.com/realms/lab/protocol/openid-connect/userinfo
      role_attribute_path: contains(grafana[*], 'Admin') && 'Admin' || contains(grafana[*], 'Editor') && 'Editor' || 'Viewer'
