apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-providerconfig-externalsecret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: keycloak-credentials
    template:
      engineVersion: v2
      data:
        credentials: |
          {
            "client_id":"admin-cli",
            "username": "admin",
            "password": "{{ .password }}",
            "url": "http://keycloak.keycloak",
            "base_path": "",
            "realm": "master"
          }
  data:
  - secretKey: password
    remoteRef:
      key: platform/keycloak/users/admin
      property: password
