{{- range .Values.users }}
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: {{ default $.Release.Name $.Values.name }}-{{ .name }}-pushsecret
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  deletionPolicy: Delete 
  secretStoreRefs:
    - name: vault-backend
      kind: ClusterSecretStore
  selector:
    secret:
      name: {{ default $.Release.Name $.Values.name }}-pguser-{{ .name }}
  data:
    - match:
        remoteRef:
          remoteKey: kv/database/postgres/users/{{ .name }}
---
{{- end }}
