apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: litellm-db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: litellm-db
  dataFrom:
    - extract:
        key: datastore/postgres/lab/litellm
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: litellm-masterkey
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: litellm-masterkey
  dataFrom:
    - extract:
        key: platform/litellm/masterkey
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: litellm-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: litellm-secret
  data:
    - secretKey: GENERIC_CLIENT_SECRET
      remoteRef:
        key: platform/keycloak/clients/litellm
        property: secret-key
    - secretKey: LITELLM_SALT_KEY
      remoteRef:
        key: platform/litellm/salt
        property: salt
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: platform/litellm/valkey
        property: password
