apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: litellm-externalsecret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: litellm-secret
  dataFrom:
  - extract:
      key: datastore/postgres/lab/litellm
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: litellm-masterkey-externalsecret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: litellm-masterkey
  dataFrom:
  - extract:
      key: platform/litellm/masterkey