apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: litellm-pushsecret
spec:
  deletionPolicy: None
  updatePolicy: IfNotExists
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: vault-backend
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: ClusterGenerator
      name: global-password-generator
  template:
    engineVersion: v2
    data:
      password: "sk-{{ .password }}"
  data:
    - match:
        secretKey: password
        remoteRef:
          property: masterkey
          remoteKey: platform/litellm/masterkey