apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: litellm-masterkey-pushsecret
spec:
  deletionPolicy: None
  updatePolicy: IfNotExists
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: vault-backend
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: ClusterGenerator
      name: global-password-generator
  template:
    engineVersion: v2
    data:
      password: "sk-{{ .password }}"
  data:
    - match:
        secretKey: password
        remoteRef:
          property: masterkey
          remoteKey: platform/litellm/masterkey
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: litellm-salt-pushsecret
spec:
  deletionPolicy: None
  updatePolicy: IfNotExists
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: vault-backend
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: ClusterGenerator
      name: strong-password-generator
  data:
    - match:
        secretKey: password
        remoteRef:
          property: salt
          remoteKey: platform/litellm/salt
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: litellm-valkey-pushsecret
spec:
  deletionPolicy: None
  updatePolicy: IfNotExists
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: vault-backend
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: ClusterGenerator
      name: strong-password-generator
  data:
    - match:
        secretKey: password
        remoteRef:
          property: password
          remoteKey: platform/litellm/valkey
