apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: coder-tf
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: coder-tf
    template:
      engineVersion: v2
      data:
        credentials: |
          {
            "coder_token": "{{ .token }}"
          }
  data:
    - secretKey: token
      remoteRef:
        key: platform/coder/users/admin
        property: token
