# Root Token hvs.GalR6fWZmFMCVoLuU3b8JPcK
config:
  stringData: |
    environment: dev
    check_interval: 15s
    max_check_interval: 30m
    vault_nodes:
      - http://vault:8200
      - http://vault:8200
      - http://vault:8200
    unseal_tokens:
      - lK1T3Ak7qbiVzgiceijSlQvZ9B4RYLRAW5RLOQj8P94=
    tls_skip_verify: true