kube-prometheus-stack:
  crds:
    enabled: false
  cleanPrometheusOperatorObjectNames: true
  alertmanager:
    enabled: false
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.tls: true
      ingressClassName: traefik
      hosts:
        - alertmanager.lab.alsheykh.com
      pathType: Prefix
      tls: 
        - secretName: alertmanager-general-tls
          hosts:
            - alertmanager.lab.alsheykh.com
  kubeApiServer:
    enabled: true
    serviceMonitor:
      metricRelabelings:
        - action: drop
          sourceLabels: ["__name__"]
          regex: (apiserver|etcd|rest_client)_request(|_sli|_slo)_duration_seconds_bucket
        - action: drop
          sourceLabels: ["__name__"]
          regex: (apiserver_response_sizes_bucket|apiserver_watch_events_sizes_bucket)
  kubelet:
    enabled: true
    serviceMonitor:
      metricRelabelings:
        - action: labeldrop
          regex: (uid)
        - action: labeldrop
          regex: (id|name)
        - action: drop
          sourceLabels: ["__name__"]
          regex: (rest_client_request_duration_seconds_bucket|rest_client_request_duration_seconds_sum|rest_client_request_duration_seconds_count)
  grafana:
    enabled: false
    forceDeployDashboards: true
  prometheus:
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.tls: true
      hosts:
        - prometheus.lab.alsheykh.com
      pathType: Prefix
      tls: 
        - secretName: prometheus-general-tls
          hosts:
            - prometheus.lab.alsheykh.com
      enableFeatures:
        - auto-gomaxprocs
        - memory-snapshot-on-shutdown
        - new-service-discovery-manager
      podMonitorSelectorNilUsesHelmValues: false
      probeSelectorNilUsesHelmValues: false
      replicaExternalLabelName: "__replica__"
      ruleSelectorNilUsesHelmValues: false
      scrapeConfigSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false
