apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - chart
  # - rate-limit-patch.yaml

# patches:
#   - target:
#       kind: Deployment
#       name: litellm
#     patch: |-
#       - op: replace
#         path: /spec/template/spec/volumes/0
#         value:
#           name: litellm-config
#           configMap:
#             name: litellm-config

# configMapGenerator:
# - name: litellm-config
#   behavior: merge
#   files:
#     - custom_sso.py