keycloak:
  production: true
  proxy: "edge"
  ingress:
    enabled: true
    ingressClassName: "traefik"
    hostname: auth.lab.alsheykh.com
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      traefik.ingress.kubernetes.io/router.tls: "true"
    tls: true
  auth:
    adminUser: admin
    existingSecret: "keycloak-secret"
    passwordSecretKey: "admin"
  adminIngress:
    enabled: true
    ingressClassName: "traefik"
    hostname: admin.auth.lab.alsheykh.com
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      traefik.ingress.kubernetes.io/router.tls: "true"
    tls: true
  keycloakConfigCli:
    enabled: true
    annotations:
      argocd.argoproj.io/hook: "PostSync"
      argocd.argoproj.io/hook-delete-policy: "HookSucceeded,BeforeHookCreation"
    configuration:
      lab.json: |
        {
          "realm": "lab",
        }
  postgresql:
    enabled: false
  externalDatabase:
    existingSecret: "keycloak-secret"
    existingSecretHostKey: "host"
    existingSecretPortKey: "port"
    existingSecretUserKey: "user"
    existingSecretDatabaseKey: "dbname"
    existingSecretPasswordKey: "password"



