apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: postgres-cluster

helmCharts:
- name: crunchy-userinit-controller
  repo: https://drummyfloyd.github.io/crunchy-userinit-controller
  version: 1.0.1
  releaseName: crunchy-userinit-controller
  valuesFile: values.yaml
  namespace: postgres-cluster
