apiVersion: v1
kind: Secret
metadata:
  name: coder-terraformrc
stringData:
  terraformrc: |
    provider_installation {
      network_mirror {
        url = "https://s3.lab.com/public/terraform/"
      }
    }
