apiVersion: generators.external-secrets.io/v1alpha1
kind: ClusterGenerator
metadata:
  name: global-password-generator
spec:
  kind: Password
  generator:
    passwordSpec:
      length: 10
      noUpper: false
      allowRepeat: false
      symbols: 0
