apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: crossplane-hrd
  repo: https://thecodingsheikh.github.io/helm-charts
  version: 0.4.1
  includeCRDs: true
  namespace: vault
  releaseName: vault-iac
  valuesFile: values.yaml